package com.ejemplo.app_ferkar.IGU;

/**
 *
 * @author kpaor
 */
public class ActPedido extends javax.swing.JFrame {

    /**
     * Creates new form ActPedido
     */
    public ActPedido() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label_title = new javax.swing.JLabel();
        label_Cliente = new javax.swing.JLabel();
        label_date = new javax.swing.JLabel();
        label_cantidad = new javax.swing.JLabel();
        textF_client = new javax.swing.JTextField();
        textF_dateDelivery = new javax.swing.JTextField();
        label_folio = new javax.swing.JLabel();
        textF_folio = new javax.swing.JTextField();
        textF_Cantidad = new javax.swing.JTextField();
        button_Clean = new javax.swing.JButton();
        button_Finish = new javax.swing.JButton();
        button_Atras = new javax.swing.JButton();
        label_pedido = new javax.swing.JLabel();
        comboBox_Estado = new javax.swing.JComboBox<>();
        label_foliosEnviados = new javax.swing.JLabel();
        textField_Clave = new javax.swing.JTextField();
        label_IDConductor = new javax.swing.JLabel();
        textF_IDConductor = new javax.swing.JTextField();
        label_Transporte = new javax.swing.JLabel();
        comboBox_transporte = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox_ModoPago = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jTextField_Folio = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_Cargas = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textField_OrdenCarga = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField_Factura = new javax.swing.JTextField();
        label_IDConductor1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1050, 800));
        setPreferredSize(new java.awt.Dimension(1050, 800));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_title.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        label_title.setText("Actualización de Pedido");
        jPanel1.add(label_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, -1, 37));

        label_Cliente.setBackground(new java.awt.Color(255, 255, 255));
        label_Cliente.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        label_Cliente.setText("Cliente:");
        jPanel1.add(label_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 90, 30));

        label_date.setBackground(new java.awt.Color(255, 255, 255));
        label_date.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        label_date.setText("Fecha Entrega:");
        jPanel1.add(label_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 140, 30));

        label_cantidad.setBackground(new java.awt.Color(255, 255, 255));
        label_cantidad.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        label_cantidad.setText("Cantidad Atados:");
        jPanel1.add(label_cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 350, 160, 30));

        textF_client.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textF_client.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textF_clientActionPerformed(evt);
            }
        });
        jPanel1.add(textF_client, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 260, 30));

        textF_dateDelivery.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(textF_dateDelivery, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 120, 30));

        label_folio.setBackground(new java.awt.Color(255, 255, 255));
        label_folio.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        label_folio.setText("Folio Pedido:");
        jPanel1.add(label_folio, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 120, 30));

        textF_folio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textF_folio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textF_folioActionPerformed(evt);
            }
        });
        jPanel1.add(textF_folio, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, 110, 30));

        textF_Cantidad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textF_Cantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textF_CantidadActionPerformed(evt);
            }
        });
        jPanel1.add(textF_Cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 350, 70, 30));

        button_Clean.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        button_Clean.setText("Limpiar");
        button_Clean.setContentAreaFilled(false);
        button_Clean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_CleanActionPerformed(evt);
            }
        });
        jPanel1.add(button_Clean, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 320, 110, 30));

        button_Finish.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        button_Finish.setText("Terminar");
        button_Finish.setContentAreaFilled(false);
        button_Finish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_FinishActionPerformed(evt);
            }
        });
        jPanel1.add(button_Finish, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 660, 110, 30));

        button_Atras.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        button_Atras.setText("Atrás");
        button_Atras.setContentAreaFilled(false);
        button_Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_AtrasActionPerformed(evt);
            }
        });
        jPanel1.add(button_Atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 700, 110, -1));

        label_pedido.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        label_pedido.setText("Estado: ");
        jPanel1.add(label_pedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 190, -1, 30));

        comboBox_Estado.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        comboBox_Estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pedido", "En producción", "Cargado", "Enviado", "Envio incompleto", "Entregado" }));
        comboBox_Estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBox_EstadoActionPerformed(evt);
            }
        });
        jPanel1.add(comboBox_Estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 190, 110, 30));

        label_foliosEnviados.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        label_foliosEnviados.setText("Clave:");
        jPanel1.add(label_foliosEnviados, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 60, 30));

        textField_Clave.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jPanel1.add(textField_Clave, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 80, 30));

        label_IDConductor.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        label_IDConductor.setText("Conductor:");
        jPanel1.add(label_IDConductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, -1, 30));

        textF_IDConductor.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        textF_IDConductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textF_IDConductorActionPerformed(evt);
            }
        });
        jPanel1.add(textF_IDConductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 60, 30));

        label_Transporte.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        label_Transporte.setText("Transporte Usado:");
        jPanel1.add(label_Transporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 240, 140, 30));

        comboBox_transporte.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        comboBox_transporte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Camioneta Grande", "Camioneta Pequeña", "Prius", "Yaris" }));
        comboBox_transporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBox_transporteActionPerformed(evt);
            }
        });
        jPanel1.add(comboBox_transporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 240, 190, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\kpaor\\Downloads\\ferkar_logo_150x90.jpg")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 150, 90));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel2.setText("# Factura:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, 80, 30));

        jComboBox_ModoPago.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jComboBox_ModoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Efectivo", "Cheque", "Transferencia" }));
        jComboBox_ModoPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_ModoPagoActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox_ModoPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 120, 30));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel3.setText("Folio Enviado:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, -1, 30));
        jPanel1.add(jTextField_Folio, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, 120, 30));

        Tabla_Cargas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Clave", "Detalle", "Tratamiento Adicional", "Folio Enviado", "Cantidad Atados"
            }
        ));
        jScrollPane1.setViewportView(Tabla_Cargas);
        if (Tabla_Cargas.getColumnModel().getColumnCount() > 0) {
            Tabla_Cargas.getColumnModel().getColumn(0).setPreferredWidth(20);
            Tabla_Cargas.getColumnModel().getColumn(1).setPreferredWidth(150);
            Tabla_Cargas.getColumnModel().getColumn(2).setPreferredWidth(20);
            Tabla_Cargas.getColumnModel().getColumn(3).setPreferredWidth(20);
            Tabla_Cargas.getColumnModel().getColumn(4).setPreferredWidth(30);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 820, 330));

        jButton1.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jButton1.setText("Agregar");
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 360, 110, 30));

        jButton2.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jButton2.setText("Eliminar");
        jButton2.setContentAreaFilled(false);
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 400, 110, 30));

        jLabel4.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Aros Cargados");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 270, -1));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel5.setText("# Orden de Carga:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 140, 140, 30));
        jPanel1.add(textField_OrdenCarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 140, 110, 30));

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel6.setText("Modo de Pago:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 110, 30));

        jTextField_Factura.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jPanel1.add(jTextField_Factura, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 190, 80, 30));

        label_IDConductor1.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        label_IDConductor1.setText("ID Conductor:");
        jPanel1.add(label_IDConductor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 801, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textF_clientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textF_clientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textF_clientActionPerformed

    private void textF_folioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textF_folioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textF_folioActionPerformed

    private void textF_CantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textF_CantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textF_CantidadActionPerformed

    private void button_CleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_CleanActionPerformed
        textField_Clave.setText("");
        jTextField_Folio.setText("");
        textF_Cantidad.setText("");
        
    }//GEN-LAST:event_button_CleanActionPerformed

    private void button_FinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_FinishActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_FinishActionPerformed

    private void button_AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_AtrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_AtrasActionPerformed

    private void comboBox_transporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBox_transporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBox_transporteActionPerformed

    private void comboBox_EstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBox_EstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBox_EstadoActionPerformed

    private void jComboBox_ModoPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_ModoPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_ModoPagoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void textF_IDConductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textF_IDConductorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textF_IDConductorActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla_Cargas;
    private javax.swing.JButton button_Atras;
    private javax.swing.JButton button_Clean;
    private javax.swing.JButton button_Finish;
    private javax.swing.JComboBox<String> comboBox_Estado;
    private javax.swing.JComboBox<String> comboBox_transporte;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox_ModoPago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField_Factura;
    private javax.swing.JTextField jTextField_Folio;
    private javax.swing.JLabel label_Cliente;
    private javax.swing.JLabel label_IDConductor;
    private javax.swing.JLabel label_IDConductor1;
    private javax.swing.JLabel label_Transporte;
    private javax.swing.JLabel label_cantidad;
    private javax.swing.JLabel label_date;
    private javax.swing.JLabel label_folio;
    private javax.swing.JLabel label_foliosEnviados;
    private javax.swing.JLabel label_pedido;
    private javax.swing.JLabel label_title;
    private javax.swing.JTextField textF_Cantidad;
    private javax.swing.JTextField textF_IDConductor;
    private javax.swing.JTextField textF_client;
    private javax.swing.JTextField textF_dateDelivery;
    private javax.swing.JTextField textF_folio;
    private javax.swing.JTextField textField_Clave;
    private javax.swing.JTextField textField_OrdenCarga;
    // End of variables declaration//GEN-END:variables
}
