/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ejemplo.app_ferkar.IGU;

/**
 *
 * @author kpaor
 */
public class MenuPedidos extends javax.swing.JFrame {

    /**
     * Creates new form MenuPedidos
     */
    public MenuPedidos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label_title = new javax.swing.JLabel();
        button_Salir = new javax.swing.JButton();
        button_ActivePedidos = new javax.swing.JButton();
        button_NewPedido = new javax.swing.JButton();
        button_UpdatePedido = new javax.swing.JButton();
        button_ArchivoPedidos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 570));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_title.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        label_title.setText("Pedidos");
        jPanel1.add(label_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, -1, 37));

        button_Salir.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        button_Salir.setText("Salir");
        button_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_SalirActionPerformed(evt);
            }
        });
        jPanel1.add(button_Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 470, 130, 40));

        button_ActivePedidos.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        button_ActivePedidos.setText("Pedidos Activos");
        button_ActivePedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_ActivePedidosActionPerformed(evt);
            }
        });
        jPanel1.add(button_ActivePedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 260, 70));

        button_NewPedido.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        button_NewPedido.setText("Nuevo Pedido");
        button_NewPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_NewPedidoActionPerformed(evt);
            }
        });
        jPanel1.add(button_NewPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, 260, 70));

        button_UpdatePedido.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        button_UpdatePedido.setText("Actualización de Pedidos");
        button_UpdatePedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_UpdatePedidoActionPerformed(evt);
            }
        });
        jPanel1.add(button_UpdatePedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 260, 70));

        button_ArchivoPedidos.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        button_ArchivoPedidos.setText("Pedidos Archivados");
        button_ArchivoPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_ArchivoPedidosActionPerformed(evt);
            }
        });
        jPanel1.add(button_ArchivoPedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, 260, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\kpaor\\Downloads\\ferkar_logo_150x90.jpg")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 150, 90));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_SalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_SalirActionPerformed

    private void button_ActivePedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_ActivePedidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_ActivePedidosActionPerformed

    private void button_NewPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_NewPedidoActionPerformed
        NuevoPedido newPedido = new NuevoPedido();
        newPedido.setVisible(true);
        newPedido.setLocationRelativeTo(null);
    }//GEN-LAST:event_button_NewPedidoActionPerformed

    private void button_UpdatePedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_UpdatePedidoActionPerformed
        ActPedido updPedido = new ActPedido();
        updPedido.setVisible(true);
        updPedido.setLocationRelativeTo(null);
    }//GEN-LAST:event_button_UpdatePedidoActionPerformed

    private void button_ArchivoPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_ArchivoPedidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_ArchivoPedidosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_ActivePedidos;
    private javax.swing.JButton button_ArchivoPedidos;
    private javax.swing.JButton button_NewPedido;
    private javax.swing.JButton button_Salir;
    private javax.swing.JButton button_UpdatePedido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label_title;
    // End of variables declaration//GEN-END:variables
}
