/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ejemplo.app_ferkar.IGU;

/**
 *
 * @author kpaor
 */
public class NuevoPedido extends javax.swing.JFrame {

    /**
     * Creates new form NuevoPedido
     */
    public NuevoPedido() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label_title = new javax.swing.JLabel();
        button_Atras = new javax.swing.JButton();
        label_Cliente = new javax.swing.JLabel();
        label_date = new javax.swing.JLabel();
        label_type_aro = new javax.swing.JLabel();
        label_quantity2 = new javax.swing.JLabel();
        label_clave = new javax.swing.JLabel();
        label_cantidad = new javax.swing.JLabel();
        checkBox_reforzar = new javax.swing.JCheckBox();
        checkBox_pintado = new javax.swing.JCheckBox();
        checkbox_galv = new javax.swing.JCheckBox();
        textField_client = new javax.swing.JTextField();
        textField_dateDelivery = new javax.swing.JTextField();
        textField_quantityTipes = new javax.swing.JTextField();
        textField_tipoAro = new javax.swing.JTextField();
        label_folio = new javax.swing.JLabel();
        textField_folio = new javax.swing.JTextField();
        textField_claveAro = new javax.swing.JTextField();
        textField_Quantity = new javax.swing.JTextField();
        button_Clean = new javax.swing.JButton();
        button_Finish = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1050, 800));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_title.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        label_title.setText("Nuevo Pedido");
        jPanel1.add(label_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, -1, 37));

        button_Atras.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        button_Atras.setText("Atrás");
        button_Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_AtrasActionPerformed(evt);
            }
        });
        jPanel1.add(button_Atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 690, 130, 50));

        label_Cliente.setBackground(new java.awt.Color(255, 255, 255));
        label_Cliente.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        label_Cliente.setText("Cliente:");
        jPanel1.add(label_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 90, 30));

        label_date.setBackground(new java.awt.Color(255, 255, 255));
        label_date.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        label_date.setText("Fecha Entrega:");
        jPanel1.add(label_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 170, 30));

        label_type_aro.setBackground(new java.awt.Color(255, 255, 255));
        label_type_aro.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        label_type_aro.setText("Tipo de Aro:");
        jPanel1.add(label_type_aro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 140, 30));

        label_quantity2.setBackground(new java.awt.Color(255, 255, 255));
        label_quantity2.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        label_quantity2.setText("Cantidad Tipos de Aro:");
        label_quantity2.setToolTipText("");
        jPanel1.add(label_quantity2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, 210, 30));

        label_clave.setBackground(new java.awt.Color(255, 255, 255));
        label_clave.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        label_clave.setText("Clave:");
        jPanel1.add(label_clave, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 360, 60, 30));

        label_cantidad.setBackground(new java.awt.Color(255, 255, 255));
        label_cantidad.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        label_cantidad.setText("Cantidad:");
        jPanel1.add(label_cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 360, 90, 30));

        checkBox_reforzar.setBackground(new java.awt.Color(255, 255, 255));
        checkBox_reforzar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        checkBox_reforzar.setText("Reforzado");
        checkBox_reforzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBox_reforzarActionPerformed(evt);
            }
        });
        jPanel1.add(checkBox_reforzar, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 350, -1, -1));

        checkBox_pintado.setBackground(new java.awt.Color(255, 255, 255));
        checkBox_pintado.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        checkBox_pintado.setText("Pintado");
        checkBox_pintado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBox_pintadoActionPerformed(evt);
            }
        });
        jPanel1.add(checkBox_pintado, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 360, -1, 20));

        checkbox_galv.setBackground(new java.awt.Color(255, 255, 255));
        checkbox_galv.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        checkbox_galv.setText("Galvanizado");
        checkbox_galv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkbox_galvActionPerformed(evt);
            }
        });
        jPanel1.add(checkbox_galv, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 370, -1, -1));

        textField_client.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textField_client.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField_clientActionPerformed(evt);
            }
        });
        jPanel1.add(textField_client, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 410, 30));

        textField_dateDelivery.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(textField_dateDelivery, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 250, 30));

        textField_quantityTipes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textField_quantityTipes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField_quantityTipesActionPerformed(evt);
            }
        });
        jPanel1.add(textField_quantityTipes, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 240, 70, 30));

        textField_tipoAro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(textField_tipoAro, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 280, 30));

        label_folio.setBackground(new java.awt.Color(255, 255, 255));
        label_folio.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        label_folio.setText("Folio Pedido:");
        jPanel1.add(label_folio, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 160, 120, 30));

        textField_folio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textField_folio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField_folioActionPerformed(evt);
            }
        });
        jPanel1.add(textField_folio, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 160, 70, 30));

        textField_claveAro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(textField_claveAro, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, 60, 30));

        textField_Quantity.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textField_Quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField_QuantityActionPerformed(evt);
            }
        });
        jPanel1.add(textField_Quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 360, 70, 30));

        button_Clean.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        button_Clean.setText("Limpiar");
        button_Clean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_CleanActionPerformed(evt);
            }
        });
        jPanel1.add(button_Clean, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 100, 120, 40));

        button_Finish.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        button_Finish.setText("Terminar");
        button_Finish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_FinishActionPerformed(evt);
            }
        });
        jPanel1.add(button_Finish, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 150, 120, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\kpaor\\Downloads\\ferkar_logo_150x90.jpg")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_AtrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_AtrasActionPerformed

    private void checkBox_reforzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBox_reforzarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBox_reforzarActionPerformed

    private void checkBox_pintadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBox_pintadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBox_pintadoActionPerformed

    private void textField_quantityTipesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField_quantityTipesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField_quantityTipesActionPerformed

    private void textField_QuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField_QuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField_QuantityActionPerformed

    private void checkbox_galvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkbox_galvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkbox_galvActionPerformed

    private void textField_folioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField_folioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField_folioActionPerformed

    private void textField_clientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField_clientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField_clientActionPerformed

    private void button_FinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_FinishActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_FinishActionPerformed

    private void button_CleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_CleanActionPerformed
        textField_Quantity.setText("");
        textField_claveAro.setText("");
        textField_client.setText("");
        textField_dateDelivery.setText("");
        textField_folio.setText("");
        textField_quantityTipes.setText("");
        textField_tipoAro.setText("");
        checkBox_pintado.setSelected(false);
        checkBox_reforzar.setSelected(false);
        checkbox_galv.setSelected(false);
    }//GEN-LAST:event_button_CleanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_Atras;
    private javax.swing.JButton button_Clean;
    private javax.swing.JButton button_Finish;
    private javax.swing.JCheckBox checkBox_pintado;
    private javax.swing.JCheckBox checkBox_reforzar;
    private javax.swing.JCheckBox checkbox_galv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label_Cliente;
    private javax.swing.JLabel label_cantidad;
    private javax.swing.JLabel label_clave;
    private javax.swing.JLabel label_date;
    private javax.swing.JLabel label_folio;
    private javax.swing.JLabel label_quantity2;
    private javax.swing.JLabel label_title;
    private javax.swing.JLabel label_type_aro;
    private javax.swing.JTextField textField_Quantity;
    private javax.swing.JTextField textField_claveAro;
    private javax.swing.JTextField textField_client;
    private javax.swing.JTextField textField_dateDelivery;
    private javax.swing.JTextField textField_folio;
    private javax.swing.JTextField textField_quantityTipes;
    private javax.swing.JTextField textField_tipoAro;
    // End of variables declaration//GEN-END:variables
}
