package com.ejemplo.app_ferkar.IGU;

import com.ejemplo.app_ferkar.App_ferkar;

/**
 *
 * @author karla_rmz_islas
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        label_title = new javax.swing.JLabel();
        label_user = new javax.swing.JLabel();
        field_user = new javax.swing.JTextField();
        separador_user = new javax.swing.JSeparator();
        label_password = new javax.swing.JLabel();
        separador_password = new javax.swing.JSeparator();
        button_entrar = new javax.swing.JButton();
        passwordField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 570));
        setPreferredSize(new java.awt.Dimension(800, 570));

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setMinimumSize(new java.awt.Dimension(800, 500));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_title.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        label_title.setText("Sistema de Administración ");
        background.add(label_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, -1, 37));

        label_user.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        label_user.setText("Usuario:");
        label_user.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        background.add(label_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 80, 20));

        field_user.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        field_user.setForeground(new java.awt.Color(204, 204, 204));
        field_user.setToolTipText("");
        field_user.setBorder(null);
        field_user.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        field_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_userActionPerformed(evt);
            }
        });
        background.add(field_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, 320, -1));

        separador_user.setForeground(new java.awt.Color(51, 51, 51));
        separador_user.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        background.add(separador_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, 300, 20));

        label_password.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        label_password.setText("Contraseña:");
        label_password.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        background.add(label_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, 110, 20));

        separador_password.setForeground(new java.awt.Color(51, 51, 51));
        separador_password.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        background.add(separador_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, 300, 20));

        button_entrar.setBackground(new java.awt.Color(204, 204, 204));
        button_entrar.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        button_entrar.setText("Entrar");
        button_entrar.setToolTipText("");
        button_entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_entrarActionPerformed(evt);
            }
        });
        background.add(button_entrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 460, 140, 50));

        passwordField.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        passwordField.setForeground(new java.awt.Color(204, 204, 204));
        passwordField.setBorder(null);
        background.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 432, 300, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\kpaor\\Downloads\\ferkar_logo_400x200.jpg")); // NOI18N
        background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 420, 230));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void field_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_userActionPerformed

    private void button_entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_entrarActionPerformed
        
        
        if(new String(passwordField.getPassword()).equals("abc")){
        
            MenuPrincipal pantalla = new MenuPrincipal();
            pantalla.setVisible(true);
            pantalla.setLocationRelativeTo(null);
        }
        /*
        MenuPrincipal pantalla = new MenuPrincipal();
        pantalla.setVisible(true);
        pantalla.setLocationRelativeTo(null);
        */
    }//GEN-LAST:event_button_entrarActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton button_entrar;
    private javax.swing.JTextField field_user;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel label_password;
    private javax.swing.JLabel label_title;
    private javax.swing.JLabel label_user;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JSeparator separador_password;
    private javax.swing.JSeparator separador_user;
    // End of variables declaration//GEN-END:variables
}
